name: upd-notion-english
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/upd-notion-english#readme
license: BSD-3-Clause
author: Author name here
maintainer: example@example.com
copyright: 2025 Author name here
category: Web
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - http-conduit
  - bytestring
  - transformers
  - scalpel
  - aeson
  - text
  - vector
  - safe-exceptions
  - aeson-qq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  upd-notion-english:
    source-dirs: src
    main: Main.hs
